select avg(ss_ext_discount_amt) from store_sales where ss_quantity       between 1      and 1.1
select avg(ss_ext_discount_amt) from store_sales where ss_quantity       between 21     and 21.1
select avg(ss_ext_discount_amt) from store_sales where ss_quantity       between 41     and 41.1
select avg(ss_ext_discount_amt) from store_sales where ss_quantity       between 61     and 61.1
select avg(ss_ext_discount_amt) from store_sales where ss_quantity       between 81     and 81.1
select avg(ss_ext_sales_price)  from store_sales where ss_quantity       between 1      and 1.1
select avg(ss_ext_sales_price)  from store_sales where ss_quantity       between 21     and 21.1
select avg(ss_ext_sales_price)  from store_sales where ss_quantity       between 41     and 41.1
select avg(ss_ext_sales_price)  from store_sales where ss_quantity       between 61     and 61.1
select avg(ss_ext_sales_price)  from store_sales where ss_quantity       between 81     and 81.1
select avg(ss_ext_list_price)   from store_sales where ss_quantity       between 1      and 1.1
select avg(ss_ext_list_price)   from store_sales where ss_quantity       between 21     and 21.1
select avg(ss_ext_list_price)   from store_sales where ss_quantity       between 41     and 41.1
select avg(ss_ext_list_price)   from store_sales where ss_quantity       between 61     and 61.1
select avg(ss_ext_list_price)   from store_sales where ss_quantity       between 81     and 81.1
select avg(ss_ext_tax)          from store_sales where ss_quantity       between 1      and 1.1
select avg(ss_ext_tax)          from store_sales where ss_quantity       between 21     and 21.1
select avg(ss_ext_tax)          from store_sales where ss_quantity       between 41     and 41.1
select avg(ss_ext_tax)          from store_sales where ss_quantity       between 61     and 61.1
select avg(ss_ext_tax)          from store_sales where ss_quantity       between 81     and 81.1
select avg(ss_net_paid)         from store_sales where ss_quantity       between 1      and 1.1
select avg(ss_net_paid)         from store_sales where ss_quantity       between 21     and 21.1
select avg(ss_net_paid)         from store_sales where ss_quantity       between 41     and 41.1
select avg(ss_net_paid)         from store_sales where ss_quantity       between 61     and 61.1
select avg(ss_net_paid)         from store_sales where ss_quantity       between 81     and 81.1
select avg(ss_net_paid_inc_tax) from store_sales where ss_quantity       between 1      and 1.1
select avg(ss_net_paid_inc_tax) from store_sales where ss_quantity       between 21     and 21.1
select avg(ss_net_paid_inc_tax) from store_sales where ss_quantity       between 41     and 41.1
select avg(ss_net_paid_inc_tax) from store_sales where ss_quantity       between 61     and 61.1
select avg(ss_net_paid_inc_tax) from store_sales where ss_quantity       between 81     and 81.1
select avg(ss_net_profit)       from store_sales where ss_quantity       between 1      and 1.1
select avg(ss_net_profit)       from store_sales where ss_quantity       between 21     and 21.1
select avg(ss_net_profit)       from store_sales where ss_quantity       between 41     and 41.1
select avg(ss_net_profit)       from store_sales where ss_quantity       between 61     and 61.1
select avg(ss_net_profit)       from store_sales where ss_quantity       between 81     and 81.1
select avg(ss_list_price)       from store_sales where ss_quantity       between 0      and 0.1
select avg(ss_list_price)       from store_sales where ss_quantity       between 6      and 6.1
select avg(ss_list_price)       from store_sales where ss_quantity       between 11     and 11.1
select avg(ss_list_price)       from store_sales where ss_quantity       between 16     and 16.1
select avg(ss_list_price)       from store_sales where ss_quantity       between 21     and 21.1
select avg(ss_list_price)       from store_sales where ss_quantity       between 26     and 26.1
select avg(ss_list_price)       from store_sales where ss_list_price     between 90     and 90.2
select avg(ss_list_price)       from store_sales where ss_list_price     between 70     and 70.2 
select avg(ss_list_price)       from store_sales where ss_list_price     between 80     and 80.2
select avg(ss_list_price)       from store_sales where ss_list_price     between 100    and 100.2
select avg(ss_list_price)       from store_sales where ss_list_price     between 110    and 110.2
select avg(ss_list_price)       from store_sales where ss_list_price     between 120    and 120.2
select avg(ss_list_price)       from store_sales where ss_coupon_amt     between 7000   and 7018  
select avg(ss_list_price)       from store_sales where ss_coupon_amt     between 8000   and 8018  
select avg(ss_list_price)       from store_sales where ss_coupon_amt     between 9000   and 9018
select avg(ss_list_price)       from store_sales where ss_coupon_amt     between 10000  and 10018
select avg(ss_list_price)       from store_sales where ss_coupon_amt     between 11000  and 11018
select avg(ss_list_price)       from store_sales where ss_coupon_amt     between 12000  and 12018
select avg(ss_list_price)       from store_sales where ss_wholesale_cost between 10     and 10.1 
select avg(ss_list_price)       from store_sales where ss_wholesale_cost between 20     and 20.1 
select avg(ss_list_price)       from store_sales where ss_wholesale_cost between 30     and 30.1
select avg(ss_list_price)       from store_sales where ss_wholesale_cost between 40     and 40.1
select avg(ss_list_price)       from store_sales where ss_wholesale_cost between 50     and 50.1
select avg(ss_list_price)       from store_sales where ss_wholesale_cost between 60     and 60.1
select avg(ws_quantity)         from web_sales   where ws_sales_price    between 100.00 and 100.3
select avg(ws_quantity)         from web_sales   where ws_sales_price    between  50.00 and 50.3
select avg(ws_quantity)         from web_sales   where ws_sales_price    between 150.00 and 150.3
select count(*) 			    from store_sales where ss_quantity 	     between 1    and 1.1
select count(*) 			    from store_sales where ss_quantity 	     between 21   and 21.1
select count(*) 			    from store_sales where ss_quantity 	     between 41   and 41.1
select count(*) 			    from store_sales where ss_quantity 	     between 61   and 61.1
select count(*) 			    from store_sales where ss_quantity 	     between 81   and 81.1
select count(ss_list_price)     from store_sales where ss_quantity 	     between 0    and 0.1
select count(ss_list_price)     from store_sales where ss_quantity 	     between 6    and 6.1
select count(ss_list_price)     from store_sales where ss_quantity 	     between 11   and 11.1
select count(ss_list_price)     from store_sales where ss_quantity 	     between 16   and 16.1
select count(ss_list_price)     from store_sales where ss_quantity 	     between 21   and 21.1
select count(ss_list_price)     from store_sales where ss_quantity 	     between 26   and 26.1
select count(ss_list_price)     from store_sales where ss_list_price     between 90   and 90.2
select count(ss_list_price)     from store_sales where ss_list_price     between 70   and 70.2 
select count(ss_list_price)     from store_sales where ss_list_price     between 80   and 80.2
select count(ss_list_price)     from store_sales where ss_list_price     between 100  and 100.2
select count(ss_list_price)     from store_sales where ss_list_price     between 110  and 110.2
select count(ss_list_price)     from store_sales where ss_list_price     between 120  and 120.2
select count(ss_list_price)     from store_sales where ss_coupon_amt     between 7000   and 7018  
select count(ss_list_price)     from store_sales where ss_coupon_amt     between 8000   and 8018  
select count(ss_list_price)     from store_sales where ss_coupon_amt     between 9000   and 9018
select count(ss_list_price)     from store_sales where ss_coupon_amt     between 10000  and 10018
select count(ss_list_price)     from store_sales where ss_coupon_amt     between 11000  and 11018
select count(ss_list_price)     from store_sales where ss_coupon_amt     between 12000  and 12018
select count(ss_list_price)     from store_sales where ss_wholesale_cost between 10     and 10.1 
select count(ss_list_price)     from store_sales where ss_wholesale_cost between 20     and 20.1 
select count(ss_list_price)     from store_sales where ss_wholesale_cost between 30     and 30.1
select count(ss_list_price)     from store_sales where ss_wholesale_cost between 40     and 40.1
select count(ss_list_price)     from store_sales where ss_wholesale_cost between 50     and 50.1
select count(ss_list_price)     from store_sales where ss_wholesale_cost between 60     and 60.1
select sum (ss_quantity)        from store_sales where ss_sales_price    between 50.00  and 50.2
select sum (ss_quantity)        from store_sales where ss_sales_price    between 100.00 and 100.2
select sum (ss_quantity)        from store_sales where ss_sales_price    between 150.00 and 150.2
select sum (ss_quantity)        from store_sales where ss_net_profit     between 0      and 20
select sum (ss_quantity)        from store_sales where ss_net_profit     between 150    and 170
select sum (ss_quantity)        from store_sales where ss_net_profit     between 50     and 70